##### Admin CMS APIs

### Root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Pariwesh",
    "lname": "Tamrakar",
    "gender": "Male",
    "dob": "01/01/1995",
    "email": "a@a.com",
    "phone": "0462718276",
    "address": "Sydney, NSW",
    "password": "1234567"
}

##### Email APIs

### verify admin email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "974941",
    "email": "ssds@hh.com"
}

### Login user
POST  http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "1234567"
}

### Logout user
POST  http://localhost:8000/api/v1/user/logout
Content-Type: application/json

{
    "accessJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzI1NzA4MTIsImV4cCI6MTYzMjU3MTcxMn0.Gv06KKkBbp95EXR4DRe7ClmFsWxEfW1Slxoeki_pxCo",
    "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzI1NzA4MTIsImV4cCI6MTYzNTE2MjgxMn0.457n-ucn23zn_kvjKuIuh-RX4JIxrtvYCHsOPw1TdFI"
}

### admin update password
POST http://localhost:8000/api/v1/user/password-update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzMwNTAzMjMsImV4cCI6MTYzMzA1MTIyM30.jcZomfiKPeLPtyplSYBDf3GFvWpik81McldtFZG5Ieo

{
    "currentPassword":"C.ronaldo7",
    "password":"1A!aa111"
}

### reset new password
POST http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json

{
    "otp": "822430",
    "email": "a@a.com" ,
    "password":"1aA!111"
}

################# Category router

### get all or single categories
GET http://localhost:8000/api/v1/category/


### Post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzI1NzMwOTMsImV4cCI6MTYzMjU3Mzk5M30.JGNnAH1bknecI8loODCdsvro_VgroT-Z5Sw7I3f0lt4

{
    "name": "Furniture",
    "parentCat": null
}

### Delete Category
DELETE http://localhost:8000/api/v1/category/

### Update category
PATCH http://localhost:8000/api/v1/category/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzI1Mzg0NDMsImV4cCI6MTYzMjUzOTM0M30.T4DIpmf-wiyVRZMKcgbxoBIvBb8GTtbnW8y7bfTZmZg

{
    "_id": "61452cee93f28fc24050fe0d",
    "name": "Houseware",
    "parentCat": null
}



################# TOKEN ROUTERS
### Get new access/refresh token
GET http://localhost:8000/api/v1/token/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE2MzI2MDkxODAsImV4cCI6MTYzNTIwMTE4MH0.w7_EWdCFOOn-F2rZrVpDKZEKDUyOefSwWt9LFKAgLKY

### user forgot password OPT request
POST  http://localhost:8000/api/v1/token/request-otp
Content-Type: application/json

{
    "email": "a@a.com"
}


