##### Admin CMS APIs

### Root api
GET http://localhost:8000/

### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Pariwesh",
    "lname": "Tamrakar",
    "gender": "Male",
    "dob": "01/01/1995",
    "email": "ssds@hh.com",
    "phone": "0462718276",
    "address": "Sydney, NSW",
    "password": "1234567"
}

##### Email APIs

### verify admin email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "974941",
    "email": "ssds@hh.com"
}



#### Catalog router

### get all or single categories
GET http://localhost:8000/api/v1/catalog/


### Post new category
POST http://localhost:8000/api/v1/catalog
Content-Type: application/json

{
    "name": "Furniture",
    "parentCat": null
}

### Delete Category
DELETE http://localhost:8000/api/v1/catalog/

### Update category
PATCH http://localhost:8000/api/v1/catalog/
Content-Type: application/json

{
    "_id": "61452cee93f28fc24050fe0d",
    "name": "Houseware",
    "parentCat": null
}